server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  reactive:
    error:
      include-message: always

spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: beans